### ISSUE TITLE
Conditional resources are assumed to be created.

### ISSUE THREAD

**Issue by v4de** [iann0036/cfn-stack-rename#1]
The current implementation compares resources from the original template with resources in the drift results. However not all resources in the template may be provisioned as they could be conditional.

In the below example template, when 'pBucketAccessControl' is 'private' the 'AWS::S3::BucketPolicy' will not exist, however the code will assume it exists since it loops through resources in the template ignoring conditions.

Example template: 
```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creates an S3 bucket configured for Private or Public an assigns permissions. 
  Distribution pointing to the S3 bucket
Parameters:
  pBucketName:
    Type: String
    Description: S3 bucket name
    Default: ''
  pBucketAccessControl:
    Type: String
    ConstraintDescription: 'Must be in either AuthenticatedRead | AwsExecRead | BucketOwnerRead | BucketOwnerFullControl | LogDeliveryWrite | Private | PublicRead'
    Description: A canned access control list (ACL) that grants predefined permissions to the bucket.
    AllowedValues:
      - AuthenticatedRead
      - AwsExecRead
      - BucketOwnerRead
      - BucketOwnerFullControl
      - LogDeliveryWrite
      - Private
      - PublicRead
      - __pBucketAccessControl__
    Default: 'Private'
  pEnableS3Notifications:
    Type: String
    Description: S3 bucket Notification
    Default: 'false'
  pS3SqsQueueArn:
    Type: String
    Description: sqs queue arn
Conditions:
  cEnableBucketPolicy: !Equals ['PublicRead', !Ref pBucketAccessControl]
  cEnableS3Notifications: !Equals ['true', !Ref pEnableS3Notifications]
  cEnablePrivateBuckets: !Equals ['Private', !Ref pBucketAccessControl]
Resources:
  rMyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: !If [cEnablePrivateBuckets, 'Private', !Ref pBucketAccessControl ]
      BucketName: !Ref pBucketName
      PublicAccessBlockConfiguration:
        !If
          - cEnablePrivateBuckets
          -
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true
          - !Ref "AWS::NoValue"
      NotificationConfiguration:
        Fn::If:
          - cEnableS3Notifications
          - QueueConfigurations:
              - Event: s3:ObjectRemoved:Delete
                Queue: !Ref pS3SqsQueueArn
              - Event: s3:ObjectCreated:*
                Queue: !Ref pS3SqsQueueArn
          - Ref: "AWS::NoValue"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - PUT
              - POST
            AllowedOrigins:
              - '*'
            MaxAge: '3000'
  rS3BucketPolicy:
    Condition: cEnableBucketPolicy
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref rMyS3Bucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref rMyS3Bucket
                - /*
Outputs:
  BucketName:
    Value: !Ref rMyS3Bucket
    Description: Name of S3 bucket
```

Suggestion: 
Get resources from cf stack instead of template for a more accurate representation of resources managed by stack.
```py
#Current
original_template = cfnclient.get_template(
    StackName=original_stack_id,
    TemplateStage='Processed'
)['TemplateBody']
```

```py
#Suggested variable rename and different method call
original_resources = cfnclient.describe_stack_resources(
    StackName=original_stack_id,
    TemplateStage='Processed'
)['StackResources']
```
